repositories:
  - name: bitnami 
    url: https://charts.bitnami.com/bitnami

releases:
  - chart: bitnami/nginx
    name: nginx
    namespace: stg
    version: 14.1.1
    labels:
      app: nginx
    values:
      - stg/values.yaml
    installed: true
    createNamespace: true